import { fetchRssItems, insertRssItems, normalizeRssSource, type RssItem } from "@/lib/ingest/rss";
import {
  fetchArtistArtwork,
  getExistingArtwork,
  insertArtworkItems,
  hasBlobEnv,
  hasWikiArtEnv,
  shuffle,
} from "@/lib/ingest/wikiart";
import { ARTIST_PAGES, RSS_FOLLOWS } from "@/lib/ingest/feeds";
import { getAllUserSubscriptions } from "@/lib/db/user";
import type { ArtworkContent } from "@/lib/db/schema";

const MAX_TOTAL_ARTWORK = 15;
const USER_ARTIST_MAX = 5;
/**
 * Cap how many NEW paintings a single default artist can contribute per run.
 * Without this, the first shuffled artist with a large corpus (e.g. Manet)
 * fills the entire `MAX_TOTAL_ARTWORK` batch alone, starving the other artists
 * and biasing the DB toward one or two names. Spreading the cap across all
 * shuffled artists yields up to `MAX_TOTAL_ARTWORK` distinct artists per run.
 */
const PER_ARTIST_PER_RUN = 1;

type StepResult = { inserted: number; feeds?: number; users?: number; artists?: number };

/**
 * Refresh the feed's `content` table with the latest entries from:
 *   - default RSS follows and WikiArt artists (global, userId = null)
 *   - each user's custom RSS feeds and artists (per-user, scoped ids)
 *
 * Replaces the old `.github/workflows/refresh-feed.yml` GitHub Action. The DB
 * is the source of truth; JSON snapshots under `src/lib/data/**` are no longer
 * written by this workflow (they remain regenerated by the ingest scripts for
 * local development).
 */
export async function refreshFeed(): Promise<{
  defaultRss: StepResult;
  userRss: StepResult;
  defaultArtwork: StepResult;
  userArtwork: StepResult;
}> {
  "use workflow";

  const defaultRss = await ingestDefaultRss();
  const userRss = await ingestUserRss();
  const defaultArtwork = await ingestDefaultArtwork();
  const userArtwork = await ingestUserArtwork();

  console.log("Refresh-feed workflow complete", {
    defaultRss,
    userRss,
    defaultArtwork,
    userArtwork,
  });

  return { defaultRss, userRss, defaultArtwork, userArtwork };
}

async function ingestDefaultRss(): Promise<StepResult> {
  "use step";

  const results = await Promise.allSettled(RSS_FOLLOWS.map((u) => fetchRssItems(u)));
  const items: RssItem[] = [];
  results.forEach((r, i) => {
    if (r.status === "fulfilled") {
      console.log(`[${RSS_FOLLOWS[i]}] ${r.value.length} items`);
      items.push(...r.value);
    } else {
      console.error(`[${RSS_FOLLOWS[i]}] failed:`, r.reason);
    }
  });

  const inserted = await insertRssItems(items, null);
  console.log(`Inserted ${inserted} global rss rows`);
  return { inserted, feeds: RSS_FOLLOWS.length };
}

async function ingestUserRss(): Promise<StepResult> {
  "use step";

  const users = await getAllUserSubscriptions();
  if (users.length === 0) return { inserted: 0, users: 0 };

  const globalSet = new Set(RSS_FOLLOWS.map(normalizeRssSource));
  const feedCache = new Map<string, RssItem[]>();
  let totalInserted = 0;

  for (const u of users) {
    const userFeeds = u.rssFeeds.filter((f) => !globalSet.has(normalizeRssSource(f)));
    for (const feedUrl of userFeeds) {
      let items = feedCache.get(feedUrl);
      if (!items) {
        try {
          items = await fetchRssItems(feedUrl);
          feedCache.set(feedUrl, items);
        } catch (e) {
          console.error(`[${feedUrl}] failed:`, (e as Error)?.message || e);
          continue;
        }
      }
      totalInserted += await insertRssItems(items, u.id);
    }
  }

  console.log(`Inserted ${totalInserted} user rss rows across ${users.length} users`);
  return { inserted: totalInserted, users: users.length };
}

async function ingestDefaultArtwork(): Promise<StepResult> {
  "use step";

  if (!hasWikiArtEnv() || !hasBlobEnv()) {
    console.warn("WikiArt/Blob env vars missing; skipping default artwork ingest");
    return { inserted: 0, artists: 0 };
  }

  const { byPaintingId, fingerprints } = await getExistingArtwork();
  const artists = shuffle(ARTIST_PAGES.slice());
  const perArtist = Math.max(
    PER_ARTIST_PER_RUN,
    Math.ceil(MAX_TOTAL_ARTWORK / artists.length),
  );
  const items: ArtworkContent[] = [];

  for (const artistUrl of artists) {
    if (items.length >= MAX_TOTAL_ARTWORK) break;
    const remaining = MAX_TOTAL_ARTWORK - items.length;
    const fetched = await fetchArtistArtwork(artistUrl, {
      maxTotal: Math.min(perArtist, remaining),
      byPaintingId,
      fingerprints,
      includeExisting: false,
    });
    items.push(...fetched);
  }

  const inserted = await insertArtworkItems(items, null);
  console.log(`Inserted ${inserted} global artwork rows`);
  return { inserted, artists: ARTIST_PAGES.length };
}

async function ingestUserArtwork(): Promise<StepResult> {
  "use step";

  if (!hasWikiArtEnv() || !hasBlobEnv()) {
    console.warn("WikiArt/Blob env vars missing; skipping user artwork ingest");
    return { inserted: 0, users: 0 };
  }

  const users = await getAllUserSubscriptions();
  if (users.length === 0) return { inserted: 0, users: 0 };

  const globalSet = new Set(ARTIST_PAGES);
  const { byPaintingId, fingerprints } = await getExistingArtwork();
  const artistCache = new Map<string, ArtworkContent[]>();
  let totalInserted = 0;

  for (const u of users) {
    const userArtists = u.artists.filter((a) => !globalSet.has(a));
    for (const artistUrl of userArtists) {
      let items = artistCache.get(artistUrl);
      if (!items) {
        items = await fetchArtistArtwork(artistUrl, {
          maxTotal: USER_ARTIST_MAX,
          byPaintingId,
          fingerprints,
          includeExisting: true,
        });
        artistCache.set(artistUrl, items);
      }
      totalInserted += await insertArtworkItems(items, u.id);
    }
  }

  console.log(`Inserted ${totalInserted} user artwork rows across ${users.length} users`);
  return { inserted: totalInserted, users: users.length };
}
